### PR TITLE
Tag field fixes

### PR DESCRIPTION
**Pull request by chillburn**
Sets the value as defined in v-model.

### CODE REVIEW

**Comment by auscaster** [comment]
This already works, no need to add this

**Comment by chillburn** [comment]
It wasn't working for me. It was returning an undefined array back to the v-model variable.

**Comment by auscaster** [comment]
Problem is your proposed method doesn't work for async loaded data, need a proper solution using `watch`

**Comment by chillburn** [comment]
This is sorted now. The watcher needed `immediate: true,` so it would run on mount.

**Pull request merged**
